version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ticket-tracker-pro:latest
    container_name: ticket-tracker-pro
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      # iTop API Configuration
      - ITOP_API_URL=${ITOP_API_URL}
      - ITOP_API_USER=${ITOP_API_USER}
      - ITOP_API_PASSWORD=${ITOP_API_PASSWORD}
      - ITOP_API_VERSION=${ITOP_API_VERSION}
      - ITOP_DEFAULT_ORG_ID=${ITOP_DEFAULT_ORG_ID}
      - ITOP_SERVICE_NAME=${ITOP_SERVICE_NAME}
      - ITOP_SERVICESUBCATEGORY_NAME=${ITOP_SERVICESUBCATEGORY_NAME}
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 